### PR TITLE
Default values now supported in graphiQL

### PR DESCRIPTION
**Pull request by abhikmitra**
Took a stab at fixing #53 . Might not be correct design , happy to iterate on this.

### CODE REVIEW

**Comment by abhikmitra** [comment]
@19majkel94 Please take a look at the approach. Once you give me a go ahead, I will fix the tests

**Comment by 19majkel94** [comment]
@abhikmitra Are you going to iterate on this PR?

**Comment by abhikmitra** [comment]
Yes , I will in the coming weekend. Got too busy with office :)

**Comment by abhikmitra** [comment]
Not getting enough time

**Pull request closed without merging**
